#!/bin/bash
# AOSP Key Generation Backend

# Set working directory to KEYS_DIR (absolute or relative to ROM root)
TARGET_DIR="${ROM_ROOT}/${KEYS_DIR}"
mkdir -p "${TARGET_DIR}"

# Sourcing keys.mk from the current directory (main/)
# This defines which keys need overrides
source ./keys.mk

# Generate Android.bp
echo "// DO NOT EDIT THIS FILE MANUALLY" > "${TARGET_DIR}/Android.bp"

for key in $(grep -o :\.\*override keys.mk | sort -u) :gmscompat_lib; do
    {
        echo ""
        echo "android_app_certificate {"
        echo "    name: \"${key:1}\","
        echo "    certificate: \"${key:1}\","
        echo "}"
    } >> "${TARGET_DIR}/Android.bp"
done

# Generate keys
for key in "${ROM_ROOT}/build/make/target/product/security/"*.pk8; do
    keyname=$(basename "$key" .pk8)
    # Skip OTA keys if requested
    if [[ "$SKIP_OTA" == "true" || "$SKIP_OTA" == "yes" ]]; then
        if [[ "$keyname" == "otakey" ]]; then
            echo "--> Skipping OTA key generation"
            continue
        fi
    fi
    ./make_key.sh "${TARGET_DIR}/${keyname}" "${KEY_SIZE:-4096}"
done

# Generate overrides
for key in $(grep -o :\.\*override keys.mk | sort -u) :gmscompat_lib; do
    ./make_key.sh "${TARGET_DIR}/${key:1}" "${KEY_SIZE:-4096}"
done
