#!/bin/bash
# AOSP Key Generation Backend

# Set working directory to KEYS_DIR
TARGET_DIR="${ROM_ROOT}/${KEYS_DIR}"
mkdir -p "${TARGET_DIR}"

# --- Makefile Handling ---
# Extract override certificates - using a more robust regex for multiline overrides
# We look for lines containing ":" after PRODUCT_CERTIFICATE_OVERRIDES
OVERRIDE_CERTS=$(grep -A 100 "PRODUCT_CERTIFICATE_OVERRIDES" keys.mk | grep -oP '(?<=:)[a-zA-Z0-9\._-]+' | sort -u)

# Generate Android.bp in target dir
echo "// DO NOT EDIT THIS FILE MANUALLY" > "${TARGET_DIR}/Android.bp"

# List of standard keys to avoid double generation or entry in Android.bp
STD_KEYS="releasekey otakey platform shared media networkstack sdk_sandbox bluetooth nfc"

for cert in $OVERRIDE_CERTS; do
    # Skip if it's a standard key
    [[ " $STD_KEYS " =~ " $cert " ]] && continue
    
    {
        echo ""
        echo "android_app_certificate {"
        echo "    name: \"$cert\","
        echo "    certificate: \"$cert\","
        echo "}"
    } >> "${TARGET_DIR}/Android.bp"
done

# GMS Compat handling
GMS_COMPAT=$(grep -c "gmscompat_lib" keys.mk)
if [[ $GMS_COMPAT -gt 0 ]]; then
    {
        echo ""
        echo "android_app_certificate {"
        echo "    name: \"gmscompat_lib.certificate.override\","
        echo "    certificate: \"gmscompat_lib.certificate.override\","
        echo "}"
    } >> "${TARGET_DIR}/Android.bp"
fi

# --- Patch keys.mk in target dir ---
# Copy original as base
cp keys.mk "${TARGET_DIR}/keys.mk"

# Update paths in the copied keys.mk using sed
sed -i "s|PRODUCT_DEFAULT_DEV_CERTIFICATE := .*|PRODUCT_DEFAULT_DEV_CERTIFICATE := ${KEYS_DIR}/releasekey|g" "${TARGET_DIR}/keys.mk"
sed -i "s|PRODUCT_OTA_PUBLIC_KEYS := .*|PRODUCT_OTA_PUBLIC_KEYS := ${KEYS_DIR}/otakey.x509.pem|g" "${TARGET_DIR}/keys.mk"
sed -i "s|PRODUCT_CERTIFICATE_GMSCOMPAT_LIB := .*|PRODUCT_CERTIFICATE_GMSCOMPAT_LIB := ${KEYS_DIR}/gmscompat_lib|g" "${TARGET_DIR}/keys.mk"
sed -i "s|PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := .*|PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := \$(dir \$(PRODUCT_DEFAULT_DEV_CERTIFICATE))|g" "${TARGET_DIR}/keys.mk"

# --- Key Generation Phase ---
echo -e "\n${BLUE}--> Processing keys in: ${NC}${TARGET_DIR}"

gen_key() {
    local name=$1
    local path="${TARGET_DIR}/${name}"
    
    if [[ -f "${path}.pk8" ]]; then
        echo -e "    ${YELLOW}[EXISTS]${NC} $name"
    else
        echo -e "    ${GREEN}[GEN]${NC} $name"
        ./make_key.sh "$path" "${KEY_SIZE:-4096}" > /dev/null 2>&1
    fi
}

# 1. Standard AOSP keys
for key in $STD_KEYS; do
    # OTA Key logic
    if [[ "$key" == "otakey" ]]; then
        if [[ "$SKIP_OTA" == "true" || "$SKIP_OTA" == "yes" ]]; then
            echo -e "    ${YELLOW}[SKIPPED]${NC} otakey"
            continue
        fi
    fi
    gen_key "$key"
done

# 2. Override keys from keys.mk
for cert in $OVERRIDE_CERTS; do
    # Skip if it's a standard key (already handled)
    [[ " $STD_KEYS " =~ " $cert " ]] && continue
    gen_key "$cert"
done

# 3. GMS Compat Overrides
if [[ $GMS_COMPAT -gt 0 ]]; then
     gen_key "gmscompat_lib.certificate.override"
     gen_key "gmscompat_lib"
fi
