#!/bin/bash
# AOSP Key Generation Backend

TARGET_DIR="${ROM_ROOT}/${KEYS_DIR}"
mkdir -p "${TARGET_DIR}"

cp keys.mk "${TARGET_DIR}/keys.mk"
OVERRIDE_CERTS=$(grep -oP '(?<=:)[a-zA-Z0-9\._-]+' keys.mk | sort -u)

echo "// DO NOT EDIT THIS FILE MANUALLY" > "${TARGET_DIR}/Android.bp"

# Added testkey to satisfy build dependencies
STD_KEYS="releasekey otakey testkey platform shared media networkstack sdk_sandbox bluetooth nfc"
GMS_OVERRIDE="gmscompat_lib.certificate.override"

for cert in $OVERRIDE_CERTS; do
    [[ " $STD_KEYS " =~ " $cert " ]] && continue
    [[ "$cert" == "$GMS_OVERRIDE" ]] && continue
    {
        echo ""
        echo "android_app_certificate {"
        echo "    name: \"$cert\","
        echo "    certificate: \"$cert\","
        echo "}"
    } >> "${TARGET_DIR}/Android.bp"
done

GMS_COMPAT=$(grep -c "gmscompat_lib" keys.mk)
if [[ $GMS_COMPAT -gt 0 ]]; then
    {
        echo ""
        echo "android_app_certificate {"
        echo "    name: \"$GMS_OVERRIDE\","
        echo "    certificate: \"$GMS_OVERRIDE\","
        echo "}"
    } >> "${TARGET_DIR}/Android.bp"
fi

sed -i "s|PRODUCT_DEFAULT_DEV_CERTIFICATE := .*|PRODUCT_DEFAULT_DEV_CERTIFICATE := ${KEYS_DIR}/releasekey|g" "${TARGET_DIR}/keys.mk"
sed -i "s|PRODUCT_OTA_PUBLIC_KEYS := .*|PRODUCT_OTA_PUBLIC_KEYS := ${KEYS_DIR}/otakey.x509.pem|g" "${TARGET_DIR}/keys.mk"
sed -i "s|PRODUCT_CERTIFICATE_GMSCOMPAT_LIB := .*|PRODUCT_CERTIFICATE_GMSCOMPAT_LIB := ${KEYS_DIR}/gmscompat_lib|g" "${TARGET_DIR}/keys.mk"
sed -i "s|PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := .*|PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := \$(dir \$(PRODUCT_DEFAULT_DEV_CERTIFICATE))|g" "${TARGET_DIR}/keys.mk"

echo -e "\n${BLUE}--> Processing keys in: ${NC}${TARGET_DIR}"

gen_key() {
    local name=$1
    local path="${TARGET_DIR}/${name}"
    
    if [[ -f "${path}.pk8" ]]; then
        echo -e "    ${YELLOW}[EXISTS]${NC} $name"
    else
        echo -e "    ${GREEN}[GEN]${NC} $name"
        ./make_key.sh "$path" "${KEY_SIZE:-4096}" > /dev/null 2>&1
    fi
}

for key in $STD_KEYS; do
    if [[ "$key" == "otakey" ]]; then
        if [[ "$SKIP_OTA" == "true" || "$SKIP_OTA" == "yes" ]]; then
            echo -e "    ${YELLOW}[SKIPPED]${NC} otakey"
            continue
        fi
    fi
    gen_key "$key"
done

for cert in $OVERRIDE_CERTS; do
    [[ " $STD_KEYS " =~ " $cert " ]] && continue
    [[ "$cert" == "$GMS_OVERRIDE" ]] && continue
    gen_key "$cert"
done

if [[ $GMS_COMPAT -gt 0 ]]; then
     gen_key "$GMS_OVERRIDE"
     gen_key "gmscompat_lib"
fi
