# SPDX-License-Identifier: Apache-2.0
# Signify Certificate Generation Logic

generate_certificates() {
    mkdir -p "$KEYS_DIR"

    if [ ! -x "$MAKE_KEY" ]; then
        red "Error: make_key not found at $MAKE_KEY"
        exit 1
    fi

    green "\n→ Generating certificates inside $KEYS_DIR..."

    # Internal helper to handle the actual generation
    _run_generation() {
        # Filter out otakey if NO_OTA is true
        local final_certs=()
        for c in "${certificates[@]}"; do
            if [[ "$NO_OTA" == "true" && "$c" == "otakey" ]]; then
                continue
            fi
            final_certs+=("$c")
        done

        # Use a patched make_key to automate and set key size
        local patched_make_key="$KEYS_DIR/make_key_patched"
        # Match 2048 as a word and skip password lines
        sed "s/\<2048\>/${key_size:-2048}/g; /Enter password/,+1d" "$MAKE_KEY" > "$patched_make_key"
        chmod +x "$patched_make_key"

        local patched_make_key_4096="$KEYS_DIR/make_key_4096"
        sed "s/\<2048\>/4096/g; /Enter password/,+1d" "$MAKE_KEY" > "$patched_make_key_4096"
        chmod +x "$patched_make_key_4096"

        set +e
        # Standard certs
        for certificate in "${final_certs[@]}"; do
            if [[ -f "$KEYS_DIR/$certificate.pk8" ]]; then
                echo "• $certificate already exists → skipped"
                continue
            fi
            echo "• Generating $certificate ..."
            bash "$patched_make_key" "$KEYS_DIR/$certificate" "$SUBJECT"
        done

        # APEX certs (Forced 4096-bit)
        for apex in "${apex_certificates[@]}"; do
            cert_name="$apex.certificate.override"
            if [[ -f "$KEYS_DIR/$cert_name.pk8" ]]; then
                echo "• $cert_name already exists → skipped"
                continue
            fi
            echo "• Generating $cert_name (4096 bit) ..."
            bash "$patched_make_key_4096" "$KEYS_DIR/$cert_name" "$SUBJECT"
        done

        # Special handling for gmscompat_lib if it exists
        if [[ " ${certificates[*]} " =~ " gmscompat_lib " ]]; then
            if [[ ! -f "$KEYS_DIR/gmscompat_lib.certificate.override.pk8" ]]; then
                echo "• Generating gmscompat_lib.certificate.override (4096 bit) ..."
                bash "$patched_make_key_4096" "$KEYS_DIR/gmscompat_lib.certificate.override" "$SUBJECT"
            fi
        fi
        set -e
        rm -f "$patched_make_key" "$patched_make_key_4096"
    }

    _run_generation
    create_releasekey
    write_android_bp
    write_product_keys_mk
    validate_keys "initial"
}

create_releasekey() {
    if [[ -f "$KEYS_DIR/releasekey.pk8" && -f "$KEYS_DIR/releasekey.x509.pem" ]]; then
        yellow "→ releasekey already exists — skipping"
        return
    fi

    green "\n→ Generating releasekey..."
    local patched_make_key="$KEYS_DIR/make_key_patched"
    # Match 2048 as a word and skip password lines
    sed "s/\<2048\>/${key_size:-2048}/g; /Enter password/,+1d" "$MAKE_KEY" > "$patched_make_key"
    chmod +x "$patched_make_key"
    
    bash "$patched_make_key" "$KEYS_DIR/releasekey" "$SUBJECT" || true
    rm -f "$patched_make_key"
}

write_android_bp() {
    green "→ Writing Android.bp..."
    {
        echo "// DO NOT EDIT THIS FILE MANUALLY"
        for apex in "${apex_certificates[@]}"; do
            echo ""
            echo "android_app_certificate {"
            echo "    name: \"$apex.certificate.override\","
            echo "    certificate: \"$apex.certificate.override\","
            echo "}"
        done
        if [[ " ${certificates[*]} " =~ " gmscompat_lib " ]]; then
            echo ""
            echo "android_app_certificate {"
            echo "    name: \"gmscompat_lib.certificate.override\","
            echo "    certificate: \"gmscompat_lib.certificate.override\","
            echo "}"
        fi
    } > "$KEYS_DIR/Android.bp"
}

write_product_keys_mk() {
    green "→ Writing product keys.mk..."
    {
        echo "PRODUCT_CERTIFICATE_OVERRIDES := "
        for apex in "${apex_certificates[@]}"; do
            echo "PRODUCT_CERTIFICATE_OVERRIDES += $apex:$apex.certificate.override"
        done
        echo ""
        echo "# Manual APK-to-APEX certificate mappings"
        local manual_overrides=(
            "AdServicesApk:com.android.adservices.api.certificate.override"
            "FederatedCompute:com.android.federatedcompute.certificate.override"
            "HealthConnectBackupRestore:com.android.health.connect.backuprestore.certificate.override"
            "HealthConnectController:com.android.healthconnect.controller.certificate.override"
            "OsuLogin:com.android.hotspot2.osulogin.certificate.override"
            "SafetyCenterResources:com.android.safetycenter.resources.certificate.override"
            "ServiceConnectivityResources:com.android.connectivity.resources.certificate.override"
            "ServiceUwbResources:com.android.uwb.resources.certificate.override"
            "ServiceWifiResources:com.android.wifi.resources.certificate.override"
            "WifiDialog:com.android.wifi.dialog.certificate.override"
        )

        for entry in "${manual_overrides[@]}"; do
            cert_name="${entry#*:}"
            if [[ -f "$KEYS_DIR/$cert_name.pk8" ]]; then
                echo "PRODUCT_CERTIFICATE_OVERRIDES += $entry"
            fi
        done

        if [[ " ${certificates[*]} " =~ " gmscompat_lib " ]]; then
            if [[ -f "$KEYS_DIR/gmscompat_lib.certificate.override.pk8" ]]; then
                echo "PRODUCT_CERTIFICATE_OVERRIDES += GmscompatLib:gmscompat_lib.certificate.override"
            fi
        fi

        echo ""
        echo "PRODUCT_DEFAULT_DEV_CERTIFICATE := $KEYS_DIR/releasekey"
        echo "PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := \$(dir \$(PRODUCT_DEFAULT_DEV_CERTIFICATE))"
        
        if [[ "$NO_OTA" == "false" ]]; then
            echo "PRODUCT_OTA_PUBLIC_KEYS := $KEYS_DIR/otakey.x509.pem"
        fi

        echo "PRODUCT_EXTRA_RECOVERY_KEYS :="
        
        if [[ " ${certificates[*]} " =~ " gmscompat_lib " ]]; then
            echo "PRODUCT_CERTIFICATE_GMSCOMPAT_LIB := $KEYS_DIR/gmscompat_lib"
        fi
    } > "$KEYS_DIR/keys.mk"
}

validate_keys() {
    local mode="$1"
    green "\n→ Running key validation..."
    local check_keys_script="$SCRIPT_DIR/check_keys.py"
    
    cp "$check_keys_script" "$KEYS_DIR/check_keys.py"
    chmod +x "$KEYS_DIR/check_keys.py"
    
    if python3 "$check_keys_script" "$KEYS_DIR"; then
        green "✓ All keys are valid!"
    else
        red "⚠️ Validation failed! Some keys are mismatched or corrupted."
        
        if [[ "$mode" == "initial" ]]; then
            if [[ "$FORCE_REPAIR" == "true" ]]; then
                yellow "→ Force mode enabled: Automatically repairing faulty keys..."
                python3 "$check_keys_script" "$KEYS_DIR" --list-faulty | while read -r faulty_base; do
                    echo "→ Repairing $faulty_base (FORCED) ..."
                    rm -f "$KEYS_DIR/$faulty_base.pk8" "$KEYS_DIR/$faulty_base.x509.pem"
                done
                _run_generation
                validate_keys "final"
            elif [[ -t 0 ]]; then
                echo ""
                yellow "Signify can attempt to fix this by deleting and regenerating ONLY the faulty keys."
                if [[ $(confirm "Do you want to auto-fix faulty keys? (Warning: This replaces them)") == "yes" ]]; then
                    # Find faulty keys from output and delete them
                    python3 "$check_keys_script" "$KEYS_DIR" --list-faulty | while read -r faulty_base; do
                        echo "→ Repairing $faulty_base ..."
                        rm -f "$KEYS_DIR/$faulty_base.pk8" "$KEYS_DIR/$faulty_base.x509.pem"
                    done
                    # Re-run generation (it will only fill the missing ones)
                    _run_generation
                    # Final validation
                    validate_keys "final"
                else
                    red "Skipping fix. Your build might fail or bootloop."
                fi
            else
                red "Non-interactive mode: Faulty keys detected. Run with --force to auto-repair."
                exit 1
            fi
        fi
    fi
}
